import type { InsightsOverview } from "@/types/insights";

export const INSIGHTS_FIXTURE: InsightsOverview = {
  generatedAt: "2026-04-16T08:30:00+05:30",
  riskProfile: {
    score: 72,
    label: "Aggressive",
    drift: 7.2,
    targetEquityPct: 70,
    currentEquityPct: 77.2,
  },
  marketSnapshot: {
    sentiment: "cautious",
    headline: "Mid & small caps cooled 4.2% this week as FII flows turned negative.",
    nifty50Change: -0.84,
    sensexChange: -0.76,
    inrUsd: 83.42,
  },
  insights: [
    {
      id: "in_rebalance_eq",
      category: "rebalance",
      severity: "warning",
      title: "Equity allocation drifted +7.2% above target",
      body: "Your portfolio is 77.2% equity vs your 70% target risk profile. Consider trimming small-cap exposure into debt to restore balance.",
      reasoning: [
        "Small-cap funds rallied 38% over the last 12 months",
        "Debt allocation slipped to 18% (target: 25%)",
        "Concentration risk in 2 schemes > 15% of portfolio each",
      ],
      potentialImpact: "Reduce drawdown risk by ~12% in a 2008-style correction",
      confidence: 88,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [
        { label: "Switch to debt", to: "/app/investor/orders/switch", variant: "primary" },
        { label: "View portfolio", to: "/app/investor/portfolio" },
      ],
    },
    {
      id: "in_tax_harvest",
      category: "tax",
      severity: "opportunity",
      title: "₹14,200 LTCG exemption still unused this FY",
      body: "You've realized only ₹42,500 of long-term equity gains so far. Harvesting up to ₹57,500 more in long-term lots would be tax-free.",
      reasoning: [
        "₹1,00,000 LTCG equity exemption resets each financial year",
        "3 long-term equity lots have unrealized gains > ₹40,000",
        "FY closes in 351 days — plan now to avoid year-end rush",
      ],
      potentialImpact: "+₹7,180 tax saved if reinvested",
      confidence: 94,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [
        { label: "Open tax simulator", to: "/app/investor/tax", variant: "primary" },
      ],
    },
    {
      id: "in_concentration",
      category: "concentration",
      severity: "warning",
      title: "Parag Parikh Flexi Cap is 28% of portfolio",
      body: "Single-scheme concentration above 25% increases idiosyncratic risk. Consider diversifying into a complementary large-cap or international fund.",
      reasoning: [
        "Top holding makes up 28% of net worth",
        "Top 3 holdings = 54% of net worth",
        "PPFAS already overlaps 18% with your Axis Bluechip",
      ],
      confidence: 81,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [
        { label: "Explore alternatives", to: "/app/investor/explore", variant: "primary" },
      ],
    },
    {
      id: "in_sip_topup",
      category: "goal",
      severity: "opportunity",
      title: "Step-up SIP by ₹4,500/month to hit retirement goal",
      body: "At your current ₹65k/month and 12% return assumption, you'll reach 94% of the inflation-adjusted target. A small step-up bridges the gap.",
      reasoning: [
        "Target: ₹3.5 Cr by Apr 2042 (inflation-adjusted)",
        "Projected corpus at current pace: ₹3.29 Cr",
        "Adding ₹4.5k/mo closes the gap at 99.6% confidence",
      ],
      potentialImpact: "+₹21 Lakh terminal corpus",
      confidence: 91,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [
        { label: "Top-up SIP", to: "/app/investor/orders/sip", variant: "primary" },
        { label: "Review goals", to: "/app/investor/goals" },
      ],
    },
    {
      id: "in_underperform",
      category: "performance",
      severity: "warning",
      title: "Quant Small Cap is underperforming peers by 11%",
      body: "Over the trailing 12 months your small-cap holding lagged the Nifty Smallcap 250 TRI. Three peer funds posted >15% over the same period.",
      reasoning: [
        "Trailing 1Y return: -8.2% vs benchmark +2.4%",
        "Fund manager change in Aug 2025",
        "Expense ratio increased from 0.62% to 0.78%",
      ],
      confidence: 76,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [
        { label: "View alternatives", to: "/app/investor/explore" },
      ],
    },
    {
      id: "in_market",
      category: "market",
      severity: "info",
      title: "Indian markets entering historically weak May–June",
      body: "Pre-budget volatility historically peaks in May. Continuing your SIPs uninterrupted is the recommended action — do not pause.",
      reasoning: [
        "Average Nifty drawdown in May (last 10 yrs): -2.1%",
        "Investors who paused SIPs lost an avg ~14% terminal returns",
        "Volatility is your friend during accumulation phase",
      ],
      confidence: 70,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [],
    },
    {
      id: "in_discovery",
      category: "discovery",
      severity: "opportunity",
      title: "3 international funds match your risk + tax profile",
      body: "You have no international diversification. Adding 8–12% in a US-Nasdaq or Global Innovation fund would reduce India-only correlation.",
      reasoning: [
        "0% international allocation today",
        "Recommended for Aggressive risk: 8–15%",
        "Top picks: Motilal Oswal Nasdaq 100 FoF, Mirae NYSE FANG+",
      ],
      potentialImpact: "Lower portfolio beta from 1.18 → 1.04",
      confidence: 82,
      generatedAt: "2026-04-16T08:30:00+05:30",
      actions: [
        { label: "Browse international", to: "/app/investor/explore" },
      ],
    },
  ],
};
