import type { Goal, GoalsOverview } from "@/types/goals";

const GOALS: Goal[] = [
  {
    id: "g_retirement",
    name: "Retirement at 55",
    category: "retirement",
    priority: "high",
    status: "on_track",
    targetAmount: 35_000_000,
    currentAmount: 9_240_000,
    monthlyContribution: 65_000,
    expectedReturnPct: 12,
    startDate: "2022-01-01",
    targetDate: "2042-04-01",
    inflationAdjusted: true,
    linkedHoldings: [
      { holdingId: "h_pp_flexi", schemeName: "Parag Parikh Flexi Cap", amc: "PPFAS", currentValue: 1_500_140, monthlySip: 25_000 },
      { holdingId: "h_axis_blue", schemeName: "Axis Bluechip", amc: "Axis MF", currentValue: 573_300, monthlySip: 15_000 },
      { holdingId: "h_mirae_mid", schemeName: "Mirae Asset Midcap", amc: "Mirae", currentValue: 421_900, monthlySip: 10_000 },
    ],
    notes: "Anchor SIPs in equity; rebalance to debt 5 years before target.",
  },
  {
    id: "g_house",
    name: "Down payment — Mumbai apartment",
    category: "house",
    priority: "high",
    status: "at_risk",
    targetAmount: 6_000_000,
    currentAmount: 2_180_000,
    monthlyContribution: 35_000,
    expectedReturnPct: 9,
    startDate: "2023-03-01",
    targetDate: "2028-06-01",
    inflationAdjusted: true,
    linkedHoldings: [
      { holdingId: "h_hdfc_corp", schemeName: "HDFC Corporate Bond", amc: "HDFC MF", currentValue: 920_400, monthlySip: 20_000 },
      { holdingId: "h_icici_liq", schemeName: "ICICI Pru Liquid", amc: "ICICI Pru", currentValue: 612_800, monthlySip: 15_000 },
    ],
  },
  {
    id: "g_child",
    name: "Child's higher education",
    category: "education",
    priority: "high",
    status: "on_track",
    targetAmount: 12_000_000,
    currentAmount: 3_120_000,
    monthlyContribution: 28_000,
    expectedReturnPct: 11,
    startDate: "2021-09-01",
    targetDate: "2036-04-01",
    inflationAdjusted: true,
    linkedHoldings: [
      { holdingId: "h_pp_flexi", schemeName: "Parag Parikh Flexi Cap", amc: "PPFAS", currentValue: 820_000, monthlySip: 18_000 },
      { holdingId: "h_quant_small", schemeName: "Quant Small Cap", amc: "Quant MF", currentValue: 487_400, monthlySip: 10_000 },
    ],
  },
  {
    id: "g_emergency",
    name: "Emergency fund (12 months)",
    category: "emergency",
    priority: "medium",
    status: "achieved",
    targetAmount: 1_200_000,
    currentAmount: 1_245_000,
    monthlyContribution: 0,
    expectedReturnPct: 6.5,
    startDate: "2022-01-01",
    targetDate: "2024-12-31",
    inflationAdjusted: false,
    linkedHoldings: [
      { holdingId: "h_icici_liq", schemeName: "ICICI Pru Liquid", amc: "ICICI Pru", currentValue: 1_245_000, monthlySip: 0 },
    ],
  },
  {
    id: "g_travel",
    name: "Europe trip 2027",
    category: "travel",
    priority: "low",
    status: "behind",
    targetAmount: 850_000,
    currentAmount: 142_000,
    monthlyContribution: 8_000,
    expectedReturnPct: 7,
    startDate: "2024-06-01",
    targetDate: "2027-05-01",
    inflationAdjusted: false,
    linkedHoldings: [
      { holdingId: "h_sbi_gold", schemeName: "SBI Gold", amc: "SBI MF", currentValue: 142_000, monthlySip: 8_000 },
    ],
  },
  {
    id: "g_car",
    name: "New car — 2026",
    category: "vehicle",
    priority: "medium",
    status: "on_track",
    targetAmount: 1_500_000,
    currentAmount: 1_087_000,
    monthlyContribution: 15_000,
    expectedReturnPct: 7.5,
    startDate: "2024-01-01",
    targetDate: "2026-11-01",
    inflationAdjusted: false,
    linkedHoldings: [
      { holdingId: "h_hdfc_corp", schemeName: "HDFC Corporate Bond", amc: "HDFC MF", currentValue: 1_087_000, monthlySip: 15_000 },
    ],
  },
];

export const GOALS_FIXTURE: GoalsOverview = {
  summary: {
    totalGoals: GOALS.length,
    totalTarget: GOALS.reduce((s, g) => s + g.targetAmount, 0),
    totalSaved: GOALS.reduce((s, g) => s + g.currentAmount, 0),
    monthlyOutflow: GOALS.reduce((s, g) => s + g.monthlyContribution, 0),
    onTrackCount: GOALS.filter((g) => g.status === "on_track" || g.status === "achieved").length,
    atRiskCount: GOALS.filter((g) => g.status === "at_risk" || g.status === "behind").length,
  },
  goals: GOALS,
};
