/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppRmIndexRouteImport } from './routes/app.rm.index'
import { Route as AppInvestorIndexRouteImport } from './routes/app.investor.index'
import { Route as AppDistributorIndexRouteImport } from './routes/app.distributor.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppRmOnboardingRouteImport } from './routes/app.rm.onboarding'
import { Route as AppRmEarningsRouteImport } from './routes/app.rm.earnings'
import { Route as AppRmClientsRouteImport } from './routes/app.rm.clients'
import { Route as AppInvestorTransactionsRouteImport } from './routes/app.investor.transactions'
import { Route as AppInvestorProfileRouteImport } from './routes/app.investor.profile'
import { Route as AppInvestorPortfolioRouteImport } from './routes/app.investor.portfolio'
import { Route as AppInvestorExploreRouteImport } from './routes/app.investor.explore'
import { Route as AppDistributorCommissionsRouteImport } from './routes/app.distributor.commissions'
import { Route as AppDistributorAumRouteImport } from './routes/app.distributor.aum'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminPayoutsRouteImport } from './routes/app.admin.payouts'
import { Route as AppAdminCommissionsRouteImport } from './routes/app.admin.commissions'
import { Route as AppInvestorOrdersSwitchRouteImport } from './routes/app.investor.orders.switch'
import { Route as AppInvestorOrdersSipRouteImport } from './routes/app.investor.orders.sip'
import { Route as AppInvestorOrdersRedeemRouteImport } from './routes/app.investor.orders.redeem'
import { Route as AppInvestorOrdersLumpsumRouteImport } from './routes/app.investor.orders.lumpsum'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRmIndexRoute = AppRmIndexRouteImport.update({
  id: '/rm/',
  path: '/rm/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorIndexRoute = AppInvestorIndexRouteImport.update({
  id: '/investor/',
  path: '/investor/',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorIndexRoute = AppDistributorIndexRouteImport.update({
  id: '/distributor/',
  path: '/distributor/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppRmOnboardingRoute = AppRmOnboardingRouteImport.update({
  id: '/rm/onboarding',
  path: '/rm/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppRmEarningsRoute = AppRmEarningsRouteImport.update({
  id: '/rm/earnings',
  path: '/rm/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppRmClientsRoute = AppRmClientsRouteImport.update({
  id: '/rm/clients',
  path: '/rm/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorTransactionsRoute = AppInvestorTransactionsRouteImport.update({
  id: '/investor/transactions',
  path: '/investor/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorProfileRoute = AppInvestorProfileRouteImport.update({
  id: '/investor/profile',
  path: '/investor/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPortfolioRoute = AppInvestorPortfolioRouteImport.update({
  id: '/investor/portfolio',
  path: '/investor/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorExploreRoute = AppInvestorExploreRouteImport.update({
  id: '/investor/explore',
  path: '/investor/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorCommissionsRoute =
  AppDistributorCommissionsRouteImport.update({
    id: '/distributor/commissions',
    path: '/distributor/commissions',
    getParentRoute: () => AppRoute,
  } as any)
const AppDistributorAumRoute = AppDistributorAumRouteImport.update({
  id: '/distributor/aum',
  path: '/distributor/aum',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayoutsRoute = AppAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCommissionsRoute = AppAdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorOrdersSwitchRoute = AppInvestorOrdersSwitchRouteImport.update({
  id: '/investor/orders/switch',
  path: '/investor/orders/switch',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorOrdersSipRoute = AppInvestorOrdersSipRouteImport.update({
  id: '/investor/orders/sip',
  path: '/investor/orders/sip',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorOrdersRedeemRoute = AppInvestorOrdersRedeemRouteImport.update({
  id: '/investor/orders/redeem',
  path: '/investor/orders/redeem',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorOrdersLumpsumRoute =
  AppInvestorOrdersLumpsumRouteImport.update({
    id: '/investor/orders/lumpsum',
    path: '/investor/orders/lumpsum',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/investor/explore': typeof AppInvestorExploreRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/investor/orders/lumpsum': typeof AppInvestorOrdersLumpsumRoute
  '/app/investor/orders/redeem': typeof AppInvestorOrdersRedeemRoute
  '/app/investor/orders/sip': typeof AppInvestorOrdersSipRoute
  '/app/investor/orders/switch': typeof AppInvestorOrdersSwitchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/investor/explore': typeof AppInvestorExploreRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/distributor': typeof AppDistributorIndexRoute
  '/app/investor': typeof AppInvestorIndexRoute
  '/app/rm': typeof AppRmIndexRoute
  '/app/investor/orders/lumpsum': typeof AppInvestorOrdersLumpsumRoute
  '/app/investor/orders/redeem': typeof AppInvestorOrdersRedeemRoute
  '/app/investor/orders/sip': typeof AppInvestorOrdersSipRoute
  '/app/investor/orders/switch': typeof AppInvestorOrdersSwitchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/admin/commissions': typeof AppAdminCommissionsRoute
  '/app/admin/payouts': typeof AppAdminPayoutsRoute
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/distributor/aum': typeof AppDistributorAumRoute
  '/app/distributor/commissions': typeof AppDistributorCommissionsRoute
  '/app/investor/explore': typeof AppInvestorExploreRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/rm/clients': typeof AppRmClientsRoute
  '/app/rm/earnings': typeof AppRmEarningsRoute
  '/app/rm/onboarding': typeof AppRmOnboardingRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/investor/orders/lumpsum': typeof AppInvestorOrdersLumpsumRoute
  '/app/investor/orders/redeem': typeof AppInvestorOrdersRedeemRoute
  '/app/investor/orders/sip': typeof AppInvestorOrdersSipRoute
  '/app/investor/orders/switch': typeof AppInvestorOrdersSwitchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/commissions'
    | '/app/admin/payouts'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/investor/explore'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/investor/orders/lumpsum'
    | '/app/investor/orders/redeem'
    | '/app/investor/orders/sip'
    | '/app/investor/orders/switch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/commissions'
    | '/app/admin/payouts'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/investor/explore'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/admin'
    | '/app/distributor'
    | '/app/investor'
    | '/app/rm'
    | '/app/investor/orders/lumpsum'
    | '/app/investor/orders/redeem'
    | '/app/investor/orders/sip'
    | '/app/investor/orders/switch'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/admin/commissions'
    | '/app/admin/payouts'
    | '/app/admin/system'
    | '/app/admin/users'
    | '/app/distributor/aum'
    | '/app/distributor/commissions'
    | '/app/investor/explore'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/transactions'
    | '/app/rm/clients'
    | '/app/rm/earnings'
    | '/app/rm/onboarding'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/investor/orders/lumpsum'
    | '/app/investor/orders/redeem'
    | '/app/investor/orders/sip'
    | '/app/investor/orders/switch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/': {
      id: '/app/rm/'
      path: '/rm'
      fullPath: '/app/rm/'
      preLoaderRoute: typeof AppRmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/': {
      id: '/app/investor/'
      path: '/investor'
      fullPath: '/app/investor/'
      preLoaderRoute: typeof AppInvestorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/': {
      id: '/app/distributor/'
      path: '/distributor'
      fullPath: '/app/distributor/'
      preLoaderRoute: typeof AppDistributorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/onboarding': {
      id: '/app/rm/onboarding'
      path: '/rm/onboarding'
      fullPath: '/app/rm/onboarding'
      preLoaderRoute: typeof AppRmOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/earnings': {
      id: '/app/rm/earnings'
      path: '/rm/earnings'
      fullPath: '/app/rm/earnings'
      preLoaderRoute: typeof AppRmEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/clients': {
      id: '/app/rm/clients'
      path: '/rm/clients'
      fullPath: '/app/rm/clients'
      preLoaderRoute: typeof AppRmClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/transactions': {
      id: '/app/investor/transactions'
      path: '/investor/transactions'
      fullPath: '/app/investor/transactions'
      preLoaderRoute: typeof AppInvestorTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/profile': {
      id: '/app/investor/profile'
      path: '/investor/profile'
      fullPath: '/app/investor/profile'
      preLoaderRoute: typeof AppInvestorProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/portfolio': {
      id: '/app/investor/portfolio'
      path: '/investor/portfolio'
      fullPath: '/app/investor/portfolio'
      preLoaderRoute: typeof AppInvestorPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/explore': {
      id: '/app/investor/explore'
      path: '/investor/explore'
      fullPath: '/app/investor/explore'
      preLoaderRoute: typeof AppInvestorExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/commissions': {
      id: '/app/distributor/commissions'
      path: '/distributor/commissions'
      fullPath: '/app/distributor/commissions'
      preLoaderRoute: typeof AppDistributorCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/aum': {
      id: '/app/distributor/aum'
      path: '/distributor/aum'
      fullPath: '/app/distributor/aum'
      preLoaderRoute: typeof AppDistributorAumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/payouts': {
      id: '/app/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/app/admin/payouts'
      preLoaderRoute: typeof AppAdminPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/commissions': {
      id: '/app/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/app/admin/commissions'
      preLoaderRoute: typeof AppAdminCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/orders/switch': {
      id: '/app/investor/orders/switch'
      path: '/investor/orders/switch'
      fullPath: '/app/investor/orders/switch'
      preLoaderRoute: typeof AppInvestorOrdersSwitchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/orders/sip': {
      id: '/app/investor/orders/sip'
      path: '/investor/orders/sip'
      fullPath: '/app/investor/orders/sip'
      preLoaderRoute: typeof AppInvestorOrdersSipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/orders/redeem': {
      id: '/app/investor/orders/redeem'
      path: '/investor/orders/redeem'
      fullPath: '/app/investor/orders/redeem'
      preLoaderRoute: typeof AppInvestorOrdersRedeemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/orders/lumpsum': {
      id: '/app/investor/orders/lumpsum'
      path: '/investor/orders/lumpsum'
      fullPath: '/app/investor/orders/lumpsum'
      preLoaderRoute: typeof AppInvestorOrdersLumpsumRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminCommissionsRoute: typeof AppAdminCommissionsRoute
  AppAdminPayoutsRoute: typeof AppAdminPayoutsRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDistributorAumRoute: typeof AppDistributorAumRoute
  AppDistributorCommissionsRoute: typeof AppDistributorCommissionsRoute
  AppInvestorExploreRoute: typeof AppInvestorExploreRoute
  AppInvestorPortfolioRoute: typeof AppInvestorPortfolioRoute
  AppInvestorProfileRoute: typeof AppInvestorProfileRoute
  AppInvestorTransactionsRoute: typeof AppInvestorTransactionsRoute
  AppRmClientsRoute: typeof AppRmClientsRoute
  AppRmEarningsRoute: typeof AppRmEarningsRoute
  AppRmOnboardingRoute: typeof AppRmOnboardingRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppDistributorIndexRoute: typeof AppDistributorIndexRoute
  AppInvestorIndexRoute: typeof AppInvestorIndexRoute
  AppRmIndexRoute: typeof AppRmIndexRoute
  AppInvestorOrdersLumpsumRoute: typeof AppInvestorOrdersLumpsumRoute
  AppInvestorOrdersRedeemRoute: typeof AppInvestorOrdersRedeemRoute
  AppInvestorOrdersSipRoute: typeof AppInvestorOrdersSipRoute
  AppInvestorOrdersSwitchRoute: typeof AppInvestorOrdersSwitchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminCommissionsRoute: AppAdminCommissionsRoute,
  AppAdminPayoutsRoute: AppAdminPayoutsRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDistributorAumRoute: AppDistributorAumRoute,
  AppDistributorCommissionsRoute: AppDistributorCommissionsRoute,
  AppInvestorExploreRoute: AppInvestorExploreRoute,
  AppInvestorPortfolioRoute: AppInvestorPortfolioRoute,
  AppInvestorProfileRoute: AppInvestorProfileRoute,
  AppInvestorTransactionsRoute: AppInvestorTransactionsRoute,
  AppRmClientsRoute: AppRmClientsRoute,
  AppRmEarningsRoute: AppRmEarningsRoute,
  AppRmOnboardingRoute: AppRmOnboardingRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppDistributorIndexRoute: AppDistributorIndexRoute,
  AppInvestorIndexRoute: AppInvestorIndexRoute,
  AppRmIndexRoute: AppRmIndexRoute,
  AppInvestorOrdersLumpsumRoute: AppInvestorOrdersLumpsumRoute,
  AppInvestorOrdersRedeemRoute: AppInvestorOrdersRedeemRoute,
  AppInvestorOrdersSipRoute: AppInvestorOrdersSipRoute,
  AppInvestorOrdersSwitchRoute: AppInvestorOrdersSwitchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
