/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppRmIndexRouteImport } from './routes/app.rm.index'
import { Route as AppInvestorIndexRouteImport } from './routes/app.investor.index'
import { Route as AppDistributorIndexRouteImport } from './routes/app.distributor.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppInvestorTransactionsRouteImport } from './routes/app.investor.transactions'
import { Route as AppInvestorProfileRouteImport } from './routes/app.investor.profile'
import { Route as AppInvestorPortfolioRouteImport } from './routes/app.investor.portfolio'
import { Route as AppInvestorExploreRouteImport } from './routes/app.investor.explore'
import { Route as AppInvestorOrdersLumpsumRouteImport } from './routes/app.investor.orders.lumpsum'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRmIndexRoute = AppRmIndexRouteImport.update({
  id: '/rm/',
  path: '/rm/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorIndexRoute = AppInvestorIndexRouteImport.update({
  id: '/investor/',
  path: '/investor/',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributorIndexRoute = AppDistributorIndexRouteImport.update({
  id: '/distributor/',
  path: '/distributor/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorTransactionsRoute = AppInvestorTransactionsRouteImport.update({
  id: '/investor/transactions',
  path: '/investor/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorProfileRoute = AppInvestorProfileRouteImport.update({
  id: '/investor/profile',
  path: '/investor/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorPortfolioRoute = AppInvestorPortfolioRouteImport.update({
  id: '/investor/portfolio',
  path: '/investor/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorExploreRoute = AppInvestorExploreRouteImport.update({
  id: '/investor/explore',
  path: '/investor/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorOrdersLumpsumRoute =
  AppInvestorOrdersLumpsumRouteImport.update({
    id: '/investor/orders/lumpsum',
    path: '/investor/orders/lumpsum',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/investor/explore': typeof AppInvestorExploreRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/investor/orders/lumpsum': typeof AppInvestorOrdersLumpsumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/investor/explore': typeof AppInvestorExploreRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/distributor': typeof AppDistributorIndexRoute
  '/app/investor': typeof AppInvestorIndexRoute
  '/app/rm': typeof AppRmIndexRoute
  '/app/investor/orders/lumpsum': typeof AppInvestorOrdersLumpsumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/investor/explore': typeof AppInvestorExploreRoute
  '/app/investor/portfolio': typeof AppInvestorPortfolioRoute
  '/app/investor/profile': typeof AppInvestorProfileRoute
  '/app/investor/transactions': typeof AppInvestorTransactionsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/distributor/': typeof AppDistributorIndexRoute
  '/app/investor/': typeof AppInvestorIndexRoute
  '/app/rm/': typeof AppRmIndexRoute
  '/app/investor/orders/lumpsum': typeof AppInvestorOrdersLumpsumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/investor/explore'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/transactions'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/investor/orders/lumpsum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/investor/explore'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/transactions'
    | '/app/admin'
    | '/app/distributor'
    | '/app/investor'
    | '/app/rm'
    | '/app/investor/orders/lumpsum'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/notifications'
    | '/app/settings'
    | '/app/investor/explore'
    | '/app/investor/portfolio'
    | '/app/investor/profile'
    | '/app/investor/transactions'
    | '/app/admin/'
    | '/app/distributor/'
    | '/app/investor/'
    | '/app/rm/'
    | '/app/investor/orders/lumpsum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rm/': {
      id: '/app/rm/'
      path: '/rm'
      fullPath: '/app/rm/'
      preLoaderRoute: typeof AppRmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/': {
      id: '/app/investor/'
      path: '/investor'
      fullPath: '/app/investor/'
      preLoaderRoute: typeof AppInvestorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/distributor/': {
      id: '/app/distributor/'
      path: '/distributor'
      fullPath: '/app/distributor/'
      preLoaderRoute: typeof AppDistributorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/transactions': {
      id: '/app/investor/transactions'
      path: '/investor/transactions'
      fullPath: '/app/investor/transactions'
      preLoaderRoute: typeof AppInvestorTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/profile': {
      id: '/app/investor/profile'
      path: '/investor/profile'
      fullPath: '/app/investor/profile'
      preLoaderRoute: typeof AppInvestorProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/portfolio': {
      id: '/app/investor/portfolio'
      path: '/investor/portfolio'
      fullPath: '/app/investor/portfolio'
      preLoaderRoute: typeof AppInvestorPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/explore': {
      id: '/app/investor/explore'
      path: '/investor/explore'
      fullPath: '/app/investor/explore'
      preLoaderRoute: typeof AppInvestorExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor/orders/lumpsum': {
      id: '/app/investor/orders/lumpsum'
      path: '/investor/orders/lumpsum'
      fullPath: '/app/investor/orders/lumpsum'
      preLoaderRoute: typeof AppInvestorOrdersLumpsumRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppInvestorExploreRoute: typeof AppInvestorExploreRoute
  AppInvestorPortfolioRoute: typeof AppInvestorPortfolioRoute
  AppInvestorProfileRoute: typeof AppInvestorProfileRoute
  AppInvestorTransactionsRoute: typeof AppInvestorTransactionsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppDistributorIndexRoute: typeof AppDistributorIndexRoute
  AppInvestorIndexRoute: typeof AppInvestorIndexRoute
  AppRmIndexRoute: typeof AppRmIndexRoute
  AppInvestorOrdersLumpsumRoute: typeof AppInvestorOrdersLumpsumRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppInvestorExploreRoute: AppInvestorExploreRoute,
  AppInvestorPortfolioRoute: AppInvestorPortfolioRoute,
  AppInvestorProfileRoute: AppInvestorProfileRoute,
  AppInvestorTransactionsRoute: AppInvestorTransactionsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppDistributorIndexRoute: AppDistributorIndexRoute,
  AppInvestorIndexRoute: AppInvestorIndexRoute,
  AppRmIndexRoute: AppRmIndexRoute,
  AppInvestorOrdersLumpsumRoute: AppInvestorOrdersLumpsumRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
